#!/bin/bash

source <path_location>/AutoGitRepo/env/bin/activate
source <path_location>/AutoGitRepo/export.sh 

# $@ is built-in function to get all argument passed
python <path_location>/AutoGitRepo/main.py "$@"
